---
abstract: 'test environment setup for development with IDE'
author:
  - 'Christian Walde <walde.christian@googlemail.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200013, CPAN::Meta::Converter version 2.110930'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-InDistDir
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Test::InDistDir:
    file: lib/Test/InDistDir.pm
    version: 1.112071
requires:
  File::Spec: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Test-InDistDir
  homepage: https://github.com/wchristian/Test-InDistDir
  repository: https://github.com/wchristian/Test-InDistDir
version: 1.112071
